
const natural = require('natural');
module.exports = {
// Sample labeled dataset
sortOrbit: (text) =>{
    
    
    // Preprocess and tokenize the text data
    labeledData = [
    { text: "What kind of cloud is this? A type of arcus cloud called a roll cloud. These rare long clouds may form near advancing cold fronts. When this happens uniformly along an extended front, a roll cloud may form.", orbit: "Atmospheric Phenomena" },
    { text: "On May 26, the Full Flower Moon was caught in this single exposure as it emerged from Earth's shadow and morning twilight began to wash over the western sky. The Earth's shadow isn't completely dark though. Faintly suffused with sunlight scattered by the atmosphere, the inner shadow gives the totally eclipsed moon a reddened appearance and the very dramatic popular moniker of a Blood Moon.", orbit: "Lunar Phenomena" },
    { text: "Will our Milky Way collide one day with its larger neighbor, the Andromeda? Most likely, yes. Careful plotting of slight displacements of M31's stars relative to background stars on recent Hubble Space Telescope images indicate that the center of M31 could be on a direct collision course with the center of our home. Once that happens, the two will become bound, dance around, and eventually merge to become one large elliptical -- over the next few billion years.", orbit: "Galactic Collisions" },
    { text: "As a powerful hurricane approaches the coast, the skies darken and the waves rise. Residents are urged to prepare for the storm's arrival and to take necessary precautions to ensure their safety. Natural disasters like hurricanes, tornadoes, and earthquakes can have a significant impact on the environment and human populations.", orbit: "Earth Weather and Natural Disasters" },
    { text: "Through the lens of a telescope, the intricate details of distant galaxies and nebulae come to life. Astrophotographers capture the beauty of the cosmos and create stunning visual representations of the universe. These captivating images highlight the cosmic artistry that exists beyond our planet.", orbit: "Astrophotography and Artistic Impressions" },
    { text: "The Mars rover Opportunity captured breathtaking images of the Martian landscape during its exploration mission. These images provide insights into the planet's geology and history. Space missions play a crucial role in advancing our understanding of other worlds and their potential for harboring life.", orbit: "Space Missions and Exploration" },
    { text: "From the sparkling blue oceans to the lush green forests, Earth's natural beauty is a source of wonder and inspiration. Satellite images capture the intricate patterns and colors of our planet. Exploring the diverse landscapes of Earth is an ongoing journey of discovery.", orbit: "Earth's Natural Beauty" },
    { text: "Astronomers have made remarkable discoveries, from new exoplanets to distant quasars. These findings reshape our understanding of the universe and spark new avenues of research. Exploring the cosmos reveals the hidden treasures and mysteries that lie beyond our planet.", orbit: "Unveiling Space Discoveries" },
      { text: "Saturn, the sixth planet from the Sun, is known for its stunning ring system. These rings are made up of countless particles of ice and rock, creating a dazzling spectacle in the night sky. Studying Saturn's rings provides insights into the planet's formation and evolution.", orbit: "Saturn's Rings" },
      { text: "The exploration of our solar system continues to yield fascinating discoveries. From the icy oceans of Jupiter's moon Europa to the volcanic landscape of Venus, each celestial body offers unique insights into the processes that shape planetary bodies.", orbit: "Solar System Explorations" },
      { text: "Cosmic phenomena such as gamma-ray bursts, pulsars, and quasars challenge our understanding of the universe. These high-energy events and enigmatic objects are often associated with extreme conditions and offer a glimpse into the most mysterious corners of space.", orbit: "Cosmic Phenomena and Mysteries" },
      { text: "Mars, often referred to as the Red Planet, has captured the imagination of scientists and space enthusiasts alike. Recent missions, including the Mars rovers, have revealed a dynamic planet with ancient river valleys, polar ice caps, and a potential history of liquid water.", orbit: "Exploring the Red Planet" },
      { text: "Exoplanets are planets that orbit stars beyond our solar system. Discoveries of exoplanets have revealed a wide range of planetary systems, some of which may harbor conditions suitable for life. Exploring exoplanets brings us closer to understanding the diversity of planetary environments.", orbit: "Exoplanet Discoveries" },
      { text: "Looking deep into space is equivalent to looking back in time. Light from distant galaxies takes millions or even billions of years to reach us. By observing these ancient light sources, astronomers can study the universe's history and evolution over cosmic time scales.", orbit: "Cosmic Time Travel" },
      { text: "The cosmos is teeming with a variety of celestial objects, from colorful nebulae to dazzling star clusters. Each of these objects tells a unique story about the processes that shape galaxies, stars, and the universe as a whole.", orbit: "Beauty of Celestial Objects" },
    //   { text: "Black holes are regions of spacetime with gravitational forces so strong that nothing, not even light, can escape their grasp. Studying black holes helps us explore the extreme limits of physics and gain insights into the fundamental nature of space and time.", orbit: "Black Hole Mysteries" },
    //   { text: "The study of planetary formation and evolution provides clues about the conditions that led to the birth of our solar system and the diversity of planetary systems beyond. By examining the building blocks of planets, scientists piece together the story of cosmic origins.", orbit: "Planetary Formation and Evolution" },
    //   { text: "Dark matter is a mysterious form of matter that does not emit light or energy. Despite its elusiveness, dark matter makes up a significant portion of the universe's mass. Scientists are actively searching for clues to unlock the nature of this enigmatic substance.", orbit: "Dark Matter Secrets" },
    //   { text: "The boundaries of our universe are marked by intriguing phenomena, such as cosmic microwave background radiation and the observable universe's size and age. These measurements provide insights into the universe's origin and the fundamental forces that govern its evolution.", orbit: "Boundaries of Space" },
    //   { text: "Dive into the heart of the Orion Nebula, a bustling stellar nursery where new stars are born. The swirling clouds of gas and dust give rise to dazzling star clusters and the famous Trapezium Cluster at its center. Nebulae like this provide a canvas for the birth and evolution of stars.", orbit: "Galactic Wonders: Nebulae and Galaxies" },
    //   { text: "Astronomers use powerful telescopes to conduct cosmic surveys, capturing vast swaths of the night sky in intricate detail. These surveys reveal the distribution of galaxies, clusters, and superclusters, shedding light on the large-scale structure of the universe.", orbit: "Mapping the Cosmos: Cosmic Surveys" },
    //   { text: "Behold the beauty of a stellar masterpiece—the Pillars of Creation in the Eagle Nebula. Towering columns of gas and dust create a breathtaking scene where new stars emerge. Astronomical images like this blend artistry and science to reveal the majesty of the cosmos.", orbit: "Celestial Artistry: Stellar Images" },
      { text: "Spiral galaxies, like the majestic Andromeda Galaxy, captivate us with their graceful arms and intricate patterns. Studying spiral galaxies provides insights into their formation, evolution, and the interplay of stars, gas, and dark matter.", orbit: "Spiral Elegance: Spiral Galaxies" },
      { text: "Zoom into a bustling metropolis of stars—a globular cluster, or cluster of galaxies. These dense collections of ancient stars form tightly bound communities that orbit galaxies. By studying globular clusters, astronomers gain clues about the early stages of galaxy formation.", orbit: "Galactic Clusters: Star Cities" },
      { text: "Rainbows, halos, and auroras are among the many atmospheric wonders that captivate our imagination. These phenomena occur due to the interaction of light with particles in the atmosphere, creating breathtaking displays of color and light.", orbit: "Atmospheric Phenomena" },
      { text: "Witness the aftermath of a stellar explosion—a supernova remnant. The intense energy released in a supernova sculpts surrounding gas and dust into intricate structures. Supernovae play a crucial role in dispersing heavy elements into space, enriching future generations of stars.", orbit: "Supernova Spectacles: Exploding Stars" },
      { text: "Explore the realm of massive galaxies, each harboring billions of stars and hosting intricate interactions. Colliding galaxies create breathtaking displays of tidal forces, gas inflows, and starbursts. These cosmic mergers shape the destinies of galaxies.", orbit: "Cosmic Giants: Massive Galaxies" },
      { text: "Peer into the heart of a quasar, a supermassive black hole surrounded by a brilliant accretion disk. Quasars are some of the brightest objects in the universe, emitting immense energy as matter spirals into the black hole. Unraveling the secrets of quasars sheds light on galaxy evolution.", orbit: "Quasar Mysteries: Active Galactic Nuclei" },
      { text: "Enter the enchanting dance of two stars in a binary system. These stellar pairs share an intimate gravitational embrace, orbiting around their common center of mass. Binary stars offer insights into stellar evolution, mass transfer, and the fate of stars.", orbit: "Stellar Dance: Binary Star Systems" },
      { text: "Discover cosmic sculptures formed by the forces of space and time. Supernova remnants, like the Crab Nebula, showcase the explosive power of dying stars. These intricate structures tell tales of stellar demise and the rebirth of new generations of stars.", orbit: "Interstellar Sculptures: Cosmic Sculptures" },
      { text: "Moon phases, from crescent to full, showcase the changing illumination of our natural satellite. These phases have influenced cultural practices and calendars throughout human history.", orbit: "Lunar Phenomena" },
       // Atmospheric Phenomena
    { text: "What kind of cloud is this? A type of arcus cloud called a roll cloud. These rare long clouds may form near advancing cold fronts. When this happens uniformly along an extended front, a roll cloud may form.", orbit: "Atmospheric Phenomena" },
    { text: "Cirrus clouds, known for their delicate and wispy appearance, often signal changes in weather patterns. Observing these high-altitude clouds can provide insights into atmospheric conditions and upcoming weather shifts.", orbit: "Atmospheric Phenomena" },
    { text: "Cumulonimbus clouds tower into the sky with immense vertical development. These thunderclouds unleash powerful lightning, thunder, and heavy rainfall, playing a vital role in Earth's water cycle and climate system.", orbit: "Atmospheric Phenomena" },

    { text: "Galactic collisions and mergers reshape the structures of galaxies. As galaxies interact and merge, their gravitational forces lead to the formation of new stars and the creation of unique galactic shapes.", orbit: "Galactic Collisions" },
    // Lunar Phenomena
    { text: "On May 26, the Full Flower Moon was caught in this single exposure as it emerged from Earth's shadow and morning twilight began to wash over the western sky. The Earth's shadow isn't completely dark though. Faintly suffused with sunlight scattered by the atmosphere, the inner shadow gives the totally eclipsed moon a reddened appearance and the very dramatic popular moniker of a Blood Moon.", orbit: "Lunar Phenomena" },
    { text: "Lunar craters and maria tell the story of the Moon's past. Impact craters reveal the history of cosmic collisions, while the smooth plains of maria offer insights into ancient volcanic activity.", orbit: "Lunar Phenomena" },
    { text: "Libration, the slight wobble of the Moon as seen from Earth, enables us to observe a small portion of the lunar far side. This phenomenon has aided astronomers in mapping the entire lunar surface.", orbit: "Lunar Phenomena" },

    // Galactic Collisions
    { text: "Tornadoes are rapidly rotating columns of air that extend from thunderstorms to the ground. These violent phenomena can cause widespread destruction and are among the most devastating natural disasters.", orbit: "Earth Weather and Natural Disasters" },
    { text: "Will our Milky Way collide one day with its larger neighbor, the Andromeda? Most likely, yes. Careful plotting of slight displacements of M31's stars relative to background stars on recent Hubble Space Telescope images indicate that the center of M31 could be on a direct collision course with the center of our home. Once that happens, the two will become bound, dance around, and eventually merge to become one large elliptical -- over the next few billion years.", orbit: "Galactic Collisions" },
    { text: "The Milky Way and Andromeda galaxies are on a collision course, destined to merge in the distant future. This event will reshape the appearance of our night sky and provide insights into the dynamics of galaxy interactions.", orbit: "Galactic Collisions" },
    { text: "Tidal forces play a crucial role during galactic collisions, stretching and distorting the shapes of galaxies. These interactions often trigger intense bursts of star formation and the birth of new stellar generations.", orbit: "Galactic Collisions" },

    // Earth Weather and Natural Disasters
    { text: "As a powerful hurricane approaches the coast, the skies darken and the waves rise. Residents are urged to prepare for the storm's arrival and to take necessary precautions to ensure their safety. Natural disasters like hurricanes, tornadoes, and earthquakes can have a significant impact on the environment and human populations.", orbit: "Earth Weather and Natural Disasters" },
    { text: "Behold the beauty of a stellar masterpiece—the Pillars of Creation in the Eagle Nebula. Towering columns of gas and dust create a breathtaking scene where new stars emerge. Astronomical images like this blend artistry and science to reveal the majesty of the cosmos.", orbit: "Astrophotography and Artistic Impressions" },
    { text: "Hurricanes, also known as cyclones or typhoons, are powerful tropical storms that form over warm ocean waters. These storms unleash strong winds, heavy rainfall, and storm surges that can have a significant impact on coastal regions.", orbit: "Earth Weather and Natural Disasters" },
    { text: "Earthquakes result from the sudden release of energy along faults in the Earth's crust. These seismic events can lead to ground shaking, tsunamis, and changes in landscape features.", orbit: "Earth Weather and Natural Disasters" },
    
    { text: "Exoplanets are planets that orbit stars beyond our solar system. Discoveries of exoplanets have revealed a wide range of planetary systems, some of which may harbor conditions suitable for life. Exploring exoplanets brings us closer to understanding the diversity of planetary environments.", orbit: "Space Missions and Exploration" },
    // Astrophotography and Artistic Impressions
    { text: "Through the lens of a telescope, the intricate details of distant galaxies and nebulae come to life. Astrophotographers capture the beauty of the cosmos and create stunning visual representations of the universe. These captivating images highlight the cosmic artistry that exists beyond our planet.", orbit: "Astrophotography and Artistic Impressions" },
    { text: "The exploration of our solar system continues to yield fascinating discoveries. From the icy oceans of Jupiter's moon Europa to the volcanic landscape of Venus, each celestial body offers unique insights into the processes that shape planetary bodies.", orbit: "Astrophotography and Artistic Impressions" },
    { text: "Dive into the heart of the Orion Nebula, a bustling stellar nursery where new stars are born. The swirling clouds of gas and dust give rise to dazzling star clusters and the famous Trapezium Cluster at its center. Nebulae like this provide a canvas for the birth and evolution of stars.", orbit: "Astrophotography and Artistic Impressions" },
    { text: "From the sparkling blue oceans to the lush green forests, Earth's natural beauty is a source of wonder and inspiration. Satellite images capture the intricate patterns and colors of our planet. Exploring the diverse landscapes of Earth is an ongoing journey of discovery.", orbit: "Earth's Natural Beauty" },

    // Space Missions and Exploration
    { text: "The Mars rover Opportunity captured breathtaking images of the Martian landscape during its exploration mission. These images provide insights into the planet's geology and history. Space missions play a crucial role in advancing our understanding of other worlds and their potential for harboring life.", orbit: "Space Missions and Exploration" },
    { text: "Astronomers have made remarkable discoveries, from new exoplanets to distant quasars. These findings reshape our understanding of the universe and spark new avenues of research. Exploring the cosmos reveals the hidden treasures and mysteries that lie beyond our planet.", orbit: "Space Missions and Exploration" },
    { text: "The study of planetary formation and evolution provides clues about the conditions that led to the birth of our solar system and the diversity of planetary systems beyond. By examining the building blocks of planets, scientists piece together the story of cosmic origins.", orbit: "Space Missions and Exploration" },
    { text: "Spiral galaxies, like the majestic Andromeda Galaxy, captivate us with their graceful arms and intricate patterns. Studying spiral galaxies provides insights into their formation, evolution, and the interplay of stars, gas, and dark matter.", orbit: "Unveiling Space Discoveries" },

    // Earth's Natural Beauty
    { text: "Looking deep into space is equivalent to looking back in time. Light from distant galaxies takes millions or even billions of years to reach us. By observing these ancient light sources, astronomers can study the universe's history and evolution over cosmic time scales.", orbit: "Earth's Natural Beauty" },
    { text: "The cosmos is teeming with a variety of celestial objects, from colorful nebulae to dazzling star clusters. Each of these objects tells a unique story about the processes that shape galaxies, stars, and the universe as a whole.", orbit: "Earth's Natural Beauty" },
    { text: "Black holes are regions of spacetime with gravitational forces so strong that nothing, not even light, can escape their grasp. Studying black holes helps us explore the extreme limits of physics and gain insights into the fundamental nature of space and time.", orbit: "Earth's Natural Beauty" },

    // Unveiling Space Discoveries
    { text: "Cassini's Grand Finale mission offered unprecedented views of Saturn's rings from close proximity. The spacecraft's findings have deepened our understanding of ring dynamics, revealing the intricate interactions between ring particles and the planet's magnetic field.", orbit: "Saturn's Rings" },
    { text: "Zoom into a bustling metropolis of stars—a globular cluster, or cluster of galaxies. These dense collections of ancient stars form tightly bound communities that orbit galaxies. By studying globular clusters, astronomers gain clues about the early stages of galaxy formation.", orbit: "Unveiling Space Discoveries" },
    { text: "Witness the aftermath of a stellar explosion—a supernova remnant. The intense energy released in a supernova sculpts surrounding gas and dust into intricate structures. Supernovae play a crucial role in dispersing heavy elements into space, enriching future generations of stars.", orbit: "Unveiling Space Discoveries" },
    { text: "Explore the realm of massive galaxies, each harboring billions of stars and hosting intricate interactions. Colliding galaxies create breathtaking displays of tidal forces, gas inflows, and starbursts. These cosmic mergers shape the destinies of galaxies.", orbit: "Unveiling Space Discoveries" },
    
    // Saturn's Rings
    { text: "Voyager 2's flyby of Neptune unveiled a dynamic planet with an active atmosphere and the striking blue hue of its methane-rich clouds. The spacecraft's observations shed light on Neptune's atmospheric composition and the unique features of its moon Triton.", orbit: "Solar System Explorations" },
    { text: "Saturn, the sixth planet from the Sun, is known for its stunning ring system. These rings are made up of countless particles of ice and rock, creating a dazzling spectacle in the night sky. Studying Saturn's rings provides insights into the planet's formation and evolution.", orbit: "Saturn's Rings" },
    { text: "Explore the breathtaking complexity of Saturn's rings—a mesmerizing tapestry of ice particles of varying sizes. These rings reveal clues about the planet's history, the interplay of gravitational forces, and the dynamic nature of space environments.", orbit: "Saturn's Rings" },
    { text: "Saturn's rings are divided into numerous distinct ringlets and gaps. These structures are the result of gravitational resonances with Saturn's moons. The study of these features provides insights into the dynamics of ring particles and moon interactions.", orbit: "Saturn's Rings" },

    // Solar System Explorations
    { text: "Pulsars are rapidly rotating neutron stars that emit beams of radiation from their magnetic poles. These beams are observed as regular pulses of light as the pulsar rotates. Pulsars provide insights into the physics of extreme densities and magnetic fields.", orbit: "Cosmic Phenomena and Mysteries" },
    { text: "The exploration of our solar system continues to yield surprising discoveries. Mars, often referred to as the Red Planet, has captured the imagination of scientists and space enthusiasts alike. Recent missions, including the Mars rovers, have revealed a dynamic planet with ancient river valleys, polar ice caps, and a potential history of liquid water.", orbit: "Solar System Explorations" },
    { text: "Jupiter's Great Red Spot is a massive storm that has persisted for centuries. Spacecraft missions like Juno have provided detailed observations of this iconic feature, offering insights into the dynamics of Jupiter's atmosphere and the forces shaping its turbulent clouds.", orbit: "Solar System Explorations" },
    { text: "The icy moon Europa, one of Jupiter's largest moons, is believed to have a subsurface ocean beneath its frozen surface. Space missions like the upcoming Europa Clipper aim to study this moon's potential habitability and the potential for life beyond Earth.", orbit: "Solar System Explorations" },

    { text: "The Curiosity rover's exploration of Gale Crater on Mars has provided evidence of ancient lakebeds and the potential for habitable environments in the planet's past. The rover's findings hint at Mars' watery history and the conditions that may have supported life.", orbit: "Exploring the Red Planet" },
    // Cosmic Phenomena and Mysteries
    { text: "Cosmic phenomena such as gamma-ray bursts, pulsars, and quasars challenge our understanding of the universe. These high-energy events and enigmatic objects are often associated with extreme conditions and offer a glimpse into the most mysterious corners of space.", orbit: "Cosmic Phenomena and Mysteries" },
    { text: "Gamma-ray bursts are among the most powerful explosions in the universe. These brief, intense bursts of gamma rays can be triggered by the collapse of massive stars or the collision of compact objects like neutron stars. Studying these events helps us probe the nature of extreme cosmic processes.", orbit: "Cosmic Phenomena and Mysteries" },
    { text: "Quasars are some of the most luminous and energetic objects in the universe. These brilliant sources of light are powered by supermassive black holes at the centers of galaxies. Studying quasars offers a window into the early universe and the conditions around massive black holes.", orbit: "Cosmic Phenomena and Mysteries" },

    { text: "The Kepler Space Telescope revolutionized our understanding of exoplanets by discovering thousands of potential exoplanet candidates. These discoveries include rocky planets in habitable zones and intriguing multi-planet systems.", orbit: "Exoplanet Discoveries" },
    // Exploring the Red Planet
    { text: "Mars, often referred to as the Red Planet, has captured the imagination of scientists and space enthusiasts alike. Recent missions, including the Mars rovers, have revealed a dynamic planet with ancient river valleys, polar ice caps, and a potential history of liquid water.", orbit: "Exploring the Red Planet" },
    { text: "The Perseverance rover, equipped with advanced scientific instruments, aims to search for signs of past life on Mars and prepare for future human exploration. This mission represents a significant step in our quest to understand the potential habitability of our neighboring planet.", orbit: "Exploring the Red Planet" },
    { text: "Mars' two small moons, Phobos and Deimos, have long puzzled scientists with their irregular shapes and origins. The upcoming Mars Sample Return mission plans to collect samples from the Martian surface, potentially shedding light on the origins of these enigmatic moons.", orbit: "Exploring the Red Planet" },

    { text: "The Hubble Deep Field images reveal galaxies from the early universe, when they were just a few hundred million years old. These snapshots provide insights into the processes that led to the formation of galaxies and the evolution of the cosmos.", orbit: "Cosmic Time Travel" },
    // Exoplanet Discoveries
    { text: "Exoplanets are planets that orbit stars beyond our solar system. Discoveries of exoplanets have revealed a wide range of planetary systems, some of which may harbor conditions suitable for life. Exploring exoplanets brings us closer to understanding the diversity of planetary environments.", orbit: "Exoplanet Discoveries" },
    { text: "The Transiting Exoplanet Survey Satellite (TESS) continues Kepler's legacy by searching for exoplanets using the transit method. TESS has already identified a variety of exoplanet candidates, providing valuable targets for further study.", orbit: "Exoplanet Discoveries" },
    { text: "Planetary systems like TRAPPIST-1 offer glimpses into the potential for Earth-like exoplanets. The discovery of seven Earth-sized planets in the habitable zone of TRAPPIST-1 raises questions about the potential for life beyond our solar system.", orbit: "Exoplanet Discoveries" },

    { text: "Nebulae are vast clouds of gas and dust that serve as the birthplaces of new stars. The stunning colors and intricate structures of these cosmic nurseries captivate our imagination and offer insights into the lifecycle of stars.", orbit: "Beauty of Celestial Objects" },
    // Cosmic Time Travel
    { text: "Looking deep into space is equivalent to looking back in time. Light from distant galaxies takes millions or even billions of years to reach us. By observing these ancient light sources, astronomers can study the universe's history and evolution over cosmic time scales.", orbit: "Cosmic Time Travel" },
    { text: "As telescopes improve, astronomers can peer even further back in time, observing galaxies as they were shortly after the Big Bang. These observations help us piece together the timeline of cosmic events and the growth of structures in the universe.", orbit: "Cosmic Time Travel" },
    { text: "The study of the cosmic microwave background radiation, the faint afterglow of the Big Bang, provides a snapshot of the universe's early moments. This radiation carries valuable information about the universe's composition, age, and evolution.", orbit: "Cosmic Time Travel" },
    
    { text: "The event horizon of a black hole marks the boundary beyond which escape is impossible. As matter falls toward the event horizon, it heats up and emits X-rays, providing astronomers with clues about the properties of black holes.", orbit: "Black Hole Mysteries" },
    // Beauty of Celestial Objects
    { text: "The cosmos is teeming with a variety of celestial objects, from colorful nebulae to dazzling star clusters. Each of these objects tells a unique story about the processes that shape galaxies, stars, and the universe as a whole.", orbit: "Beauty of Celestial Objects" },
    { text: "Stellar clusters are gatherings of stars that share a common origin. Open clusters, like the Pleiades, and globular clusters, like Omega Centauri, showcase the diverse arrangements and ages of stars across the universe.", orbit: "Beauty of Celestial Objects" },
    { text: "The Orion Nebula, one of the most iconic nebulae, is a region of active star formation. The nebula's intricate tendrils of gas and dust give rise to new stars, and its beauty has made it a favorite target for both amateur and professional astronomers.", orbit: "Beauty of Celestial Objects" },
    { text: "The study of planetary formation and evolution provides clues about the conditions that led to the birth of our solar system and the diversity of planetary systems beyond. By examining the building blocks of planets, scientists piece together the story of cosmic origins.", orbit: "Planetary Formation and Evolution" },
    
    // Black Hole Mysteries
    { text: "Black holes are regions of spacetime with gravitational forces so strong that nothing, not even light, can escape their grasp. Studying black holes helps us explore the extreme limits of physics and gain insights into the fundamental nature of space and time.", orbit: "Black Hole Mysteries" },
    { text: "Supermassive black holes, found at the centers of galaxies, can have masses millions to billions of times that of the Sun. These enigmatic objects play a crucial role in shaping galactic dynamics and influencing their host galaxies.", orbit: "Black Hole Mysteries" },
    { text: "Black holes can be detected through their gravitational influence on nearby stars or by observing the radiation emitted by accretion disks. Studying these phenomena allows scientists to explore the nature of gravity and spacetime.", orbit: "Black Hole Mysteries" },

    // Planetary Formation and Evolution
    { text: "Experiments are underway to detect dark matter particles using various approaches, such as direct detection and accelerator-based experiments. Detecting dark matter would provide insights into its properties and help us understand its role in shaping cosmic structures.", orbit: "Dark Matter Secrets" },
    { text: "Protoplanetary disks are flat structures of gas and dust that surround young stars. Inside these disks, planetesimals collide and merge to form planets. The composition and structure of these disks influence the characteristics of the planets that form.", orbit: "Planetary Formation and Evolution" },
    { text: "Giant gas planets, like Jupiter, form far from their host stars in regions rich in volatile elements. Terrestrial planets, like Earth, form closer to the star and consist of denser materials. The positioning of planets in a system is influenced by the properties of the protoplanetary disk.", orbit: "Planetary Formation and Evolution" },
    { text: "The study of exoplanets reveals a diverse range of planetary systems with various sizes, compositions, and orbital characteristics. By analyzing these systems, astronomers gain insights into the processes that shape the architecture of planetary systems.", orbit: "Planetary Formation and Evolution" },

    // Dark Matter Secrets
    { text: "The observable universe is limited by the speed of light, and we can only observe objects within our cosmic horizon. As we look farther into space, we are also looking back in time to earlier epochs of the universe.", orbit: "Boundaries of Space" },
    { text: "Dark matter is a mysterious form of matter that does not emit light or energy. Despite its elusiveness, dark matter makes up a significant portion of the universe's mass. Scientists are actively searching for clues to unlock the nature of this enigmatic substance.", orbit: "Dark Matter Secrets" },
    { text: "Observations of galaxy rotation curves and gravitational lensing reveal the presence of dark matter in the universe. Unlike ordinary matter, dark matter does not interact through electromagnetic forces, making it challenging to detect directly.", orbit: "Dark Matter Secrets" },
    { text: "Dark matter is believed to influence the formation of galaxies and galaxy clusters by providing the gravitational scaffolding that holds them together. Understanding dark matter's role is crucial for comprehending the evolution of cosmic structures.", orbit: "Dark Matter Secrets" },

    // Boundaries of Space
    { text: "Galaxies are vast cosmic islands composed of stars, gas, dust, and dark matter. The Milky Way, our home galaxy, is just one of billions of galaxies in the universe. Exploring the diversity of galaxies provides insights into their formation and evolution.", orbit: "Galactic Wonders: Nebulae and Galaxies" },
    { text: "The boundaries of our universe are marked by intriguing phenomena, such as cosmic microwave background radiation and the observable universe's size and age. These measurements provide insights into the universe's origin and the fundamental forces that govern its evolution.", orbit: "Boundaries of Space" },
    { text: "The cosmic microwave background radiation is the afterglow of the Big Bang, observed as a faint glow in all directions of the universe. It carries information about the universe's early conditions and the density fluctuations that led to the formation of galaxies and structures.", orbit: "Boundaries of Space" },
    { text: "Cosmological redshift, caused by the expansion of space, leads to the observed redshift of distant galaxies' light. Measuring redshifts allows astronomers to estimate the distances to galaxies and infer the expansion rate of the universe.", orbit: "Boundaries of Space" },
    { text: "Astronomers use powerful telescopes to conduct cosmic surveys, capturing vast swaths of the night sky in intricate detail. These surveys reveal the distribution of galaxies, clusters, and superclusters, shedding light on the large-scale structure of the universe.", orbit: "Mapping the Cosmos: Cosmic Surveys" },

    // Galactic Wonders: Nebulae and Galaxies
    { text: "Dive into the heart of the Orion Nebula, a bustling stellar nursery where new stars are born. The swirling clouds of gas and dust give rise to dazzling star clusters and the famous Trapezium Cluster at its center. Nebulae like this provide a canvas for the birth and evolution of stars.", orbit: "Galactic Wonders: Nebulae and Galaxies" },
    { text: "Nebulae come in various types, including emission nebulae, reflection nebulae, and dark nebulae. These regions of interstellar gas and dust showcase the processes of star formation, illumination by nearby stars, and absorption of light.", orbit: "Galactic Wonders: Nebulae and Galaxies" },
    { text: "Active galaxies, such as Seyfert galaxies and quasars, emit intense radiation from their central regions. The energetic emissions arise from the interaction between matter and supermassive black holes at their cores.", orbit: "Galactic Wonders: Nebulae and Galaxies" },

    { text: "Astrophotographers use advanced imaging techniques to capture the colors, details, and structures of celestial objects. These images not only showcase the natural beauty of the universe but also contribute to scientific research and public engagement.", orbit: "Celestial Artistry: Stellar Images" },
    // Mapping the Cosmos: Cosmic Surveys
    { text: "Galaxy surveys, such as the Sloan Digital Sky Survey, have provided 3D maps of galaxies in the universe. These maps allow astronomers to study the distribution of matter, the cosmic web, and the clustering of galaxies.", orbit: "Mapping the Cosmos: Cosmic Surveys" },
    { text: "The Pan-STARRS survey aims to map the entire sky to identify and study a wide range of celestial objects, including asteroids, comets, and distant galaxies. Such surveys contribute to our understanding of cosmic evolution and dynamics.", orbit: "Mapping the Cosmos: Cosmic Surveys" },
    { text: "Surveys of cosmic microwave background radiation, such as the Planck mission, provide detailed maps of the universe's early conditions. These maps offer insights into the universe's composition, structure, and the seeds of galaxy formation.", orbit: "Mapping the Cosmos: Cosmic Surveys" },

    // Celestial Artistry: Stellar Images
    { text: "Behold the beauty of a stellar masterpiece—the Pillars of Creation in the Eagle Nebula. Towering columns of gas and dust create a breathtaking scene where new stars emerge. Astronomical images like this blend artistry and science to reveal the majesty of the cosmos.", orbit: "Celestial Artistry: Stellar Images" },
    { text: "The intricate arms and patterns of spiral galaxies are a testament to the underlying physical processes that govern their evolution. The balance between gravitational forces, gas dynamics, and star formation contributes to their captivating appearance.", orbit: "Spiral Elegance: Spiral Galaxies" },
    { text: "Time-lapse and long-exposure photography reveal the motion of celestial objects, such as star trails and the rotation of planets. These images provide visual insights into the dynamics of the cosmos and the Earth's place in the universe.", orbit: "Celestial Artistry: Stellar Images" },
    { text: "Astronomical images often reveal the intricate connections between celestial objects. Capturing galaxies, nebulae, and star clusters in a single frame showcases the rich tapestry of the cosmos and the relationships between its diverse components.", orbit: "Celestial Artistry: Stellar Images" },

    // Spiral Elegance: Spiral Galaxies
    { text: "Open star clusters, like the Pleiades, are groups of stars born from the same molecular cloud. These clusters offer a window into the early stages of stellar evolution and the interactions between young stars.", orbit: "Galactic Clusters: Star Cities" },
    { text: "Spiral galaxies, like the majestic Andromeda Galaxy, captivate us with their graceful arms and intricate patterns. Studying spiral galaxies provides insights into their formation, evolution, and the interplay of stars, gas, and dark matter.", orbit: "Spiral Elegance: Spiral Galaxies" },
    { text: "Galaxies like the Whirlpool Galaxy (M51) showcase the beauty of gravitational interactions. As galaxies pass close to one another, their gravitational forces can trigger the formation of new stars and reshape their structures.", orbit: "Spiral Elegance: Spiral Galaxies" },
    { text: "Barred spiral galaxies, characterized by a central bar-shaped structure, offer unique views of galactic dynamics. These galaxies often host regions of intense star formation along their bars.", orbit: "Spiral Elegance: Spiral Galaxies" },
  
    { text: "Type Ia supernovae, caused by the explosion of white dwarf stars in binary systems, serve as cosmic beacons for measuring distances across the universe. These explosions have contributed to the discovery of the accelerated expansion of the cosmos.", orbit: "Supernova Spectacles: Exploding Stars" },
    // Galactic Clusters: Star Cities
    { text: "Zoom into a bustling metropolis of stars—a globular cluster, or cluster of galaxies. These dense collections of ancient stars form tightly bound communities that orbit galaxies. By studying globular clusters, astronomers gain clues about the early stages of galaxy formation.", orbit: "Galactic Clusters: Star Cities" },
    { text: "Globular clusters, like Omega Centauri, contain hundreds of thousands to millions of stars packed closely together. These clusters provide insights into stellar evolution, the dynamics of densely packed systems, and the history of their host galaxies.", orbit: "Galactic Clusters: Star Cities" },
    { text: "Superclusters are vast regions of space that contain clusters of galaxies. These structures reveal the large-scale distribution of matter in the universe and provide insights into the cosmic web of galaxies and voids.", orbit: "Galactic Clusters: Star Cities" },
  
    { text: "Elliptical galaxies, shaped like spheres or ellipsoids, are often found at the centers of galaxy clusters. These galaxies are believed to form through the merger of smaller galaxies and exhibit different characteristics from spiral galaxies.", orbit: "Cosmic Giants: Massive Galaxies" },
    // Supernova Spectacles: Exploding Stars
    { text: "Witness the aftermath of a stellar explosion—a supernova remnant. The intense energy released in a supernova sculpts surrounding gas and dust into intricate structures. Supernovae play a crucial role in dispersing heavy elements into space, enriching future generations of stars.", orbit: "Supernova Spectacles: Exploding Stars" },
    { text: "Massive stars end their lives in brilliant supernova explosions. These events release tremendous energy and create shockwaves that trigger the formation of new stars and influence the surrounding interstellar medium.", orbit: "Supernova Spectacles: Exploding Stars" },
    { text: "Supernovae are a primary source of heavy elements in the universe, such as iron and gold. The explosions of massive stars disperse these elements into space, enriching interstellar clouds and contributing to the diversity of stellar systems.", orbit: "Supernova Spectacles: Exploding Stars" },
  
    { text: "Quasars are powered by the accretion of matter onto supermassive black holes. The intense gravitational forces and friction generate tremendous energy, causing quasars to outshine entire galaxies for a brief period of time.", orbit: "Quasar Mysteries: Active Galactic Nuclei" },
    // Cosmic Giants: Massive Galaxies
    { text: "Explore the realm of massive galaxies, each harboring billions of stars and hosting intricate interactions. Colliding galaxies create breathtaking displays of tidal forces, gas inflows, and starbursts. These cosmic mergers shape the destinies of galaxies.", orbit: "Cosmic Giants: Massive Galaxies" },
    { text: "Galactic cannibalism occurs when a larger galaxy absorbs a smaller one. The process of galaxy mergers and interactions leads to the formation of new stars, the growth of supermassive black holes, and the redistribution of gas and stars.", orbit: "Cosmic Giants: Massive Galaxies" },
    { text: "Massive galaxies host supermassive black holes at their centers. These black holes can unleash powerful jets of energy and influence the evolution of their host galaxies through processes such as feedback and quenching of star formation.", orbit: "Cosmic Giants: Massive Galaxies" },
  
    // Quasar Mysteries: Active Galactic Nuclei
    { text: "Stellar companions in binary systems can influence each other's evolution. Mass transfer, tidal forces, and interactions during various phases of stellar life can lead to changes in the stars' sizes, temperatures, and eventual fates.", orbit: "Stellar Dance: Binary Star Systems" },
    { text: "Peer into the heart of a quasar, a supermassive black hole surrounded by a brilliant accretion disk. Quasars are some of the brightest objects in the universe, emitting immense energy as matter spirals into the black hole. Unraveling the secrets of quasars sheds light on galaxy evolution.", orbit: "Quasar Mysteries: Active Galactic Nuclei" },
    { text: "Quasars are observed at various distances, offering glimpses into the early universe. Studying quasars helps astronomers understand the growth of galaxies, the interplay between supermassive black holes and their host galaxies, and the cosmic history of accretion events.", orbit: "Quasar Mysteries: Active Galactic Nuclei" },
    { text: "Active galactic nuclei encompass a range of phenomena, from quasars to blazars and Seyfert galaxies. These energetic sources provide insights into the extreme conditions around supermassive black holes and the mechanisms that drive their energetic emissions.", orbit: "Quasar Mysteries: Active Galactic Nuclei" },
    { text: "Discover cosmic sculptures formed by the forces of space and time. Supernova remnants, like the Crab Nebula, showcase the explosive power of dying stars. These intricate structures tell tales of stellar demise and the rebirth of new generations of stars.", orbit: "Interstellar Sculptures: Cosmic Sculptures" },
    
    // Stellar Dance: Binary Star Systems
    { text: "Enter the enchanting dance of two stars in a binary system. These stellar pairs share an intimate gravitational embrace, orbiting around their common center of mass. Binary stars offer insights into stellar evolution, mass transfer, and the fate of stars.", orbit: "Stellar Dance: Binary Star Systems" },
    { text: "Binary star systems come in various forms, from close binaries with stars almost touching to wide binaries with significant separations. The gravitational interactions between these stars shape their characteristics and lifetimes.", orbit: "Stellar Dance: Binary Star Systems" },
    { text: "Binary systems can exhibit eclipses as one star passes in front of the other from our line of sight. These eclipsing binaries provide valuable information about the stars' properties, such as their sizes, masses, and orbital dynamics.", orbit: "Stellar Dance: Binary Star Systems" },

    // Interstellar Sculptures: Cosmic Sculptures
    { text: "Planetary nebulae are the colorful shells of gas ejected by dying stars in their final stages. These nebulae, like the Helix Nebula, reveal the star's outer layers and the complex processes that shape the interstellar medium.", orbit: "Interstellar Sculptures: Cosmic Sculptures" },
    { text: "The Veil Nebula is a spectacular supernova remnant divided into the Eastern and Western Veil. The intricate filaments and shockwaves in this nebula reflect the dramatic events that occurred when a massive star exploded.", orbit: "Interstellar Sculptures: Cosmic Sculptures" },
    { text: "The Carina Nebula, a vast star-forming region, showcases the dynamic interplay between young, massive stars and their surrounding gas and dust. The nebula's pillars, jets, and clusters provide a glimpse into the chaotic beauty of cosmic birthplaces.", orbit: "Interstellar Sculptures: Cosmic Sculptures" },
];
    
const tokenizer = new natural.WordTokenizer();
const processedData = labeledData.map(item => ({
  tokens: tokenizer.tokenize(item.text.toLowerCase()),
  orbit: item.orbit
}));

// Create and train the classifier
const classifier = new natural.BayesClassifier();
processedData.forEach(item => classifier.addDocument(item.tokens, item.orbit));
classifier.train();

// Predict the topic for a new post
const newPostText = text;
const classifications = classifier.getClassifications(tokenizer.tokenize(newPostText.toLowerCase()));
const predictedOrbit = classifications[0].label;
const confidence = classifications[0].value;
return ({
    predictedOrbit, confidence
})
}
}
